### ISSUE TITLE
How to control animation (stop, pause, resume) ?

### ISSUE THREAD

**Issue by yankeen** [revoltera/polygonizr#1]
Hi,

Great code. Tell me please how to control the animation - stop, pause, resume?

Thanks

**Comment by martin-lundgren** [comment]
Hi,

Glad you like it! (: I have updated the code, and you are now able to stop/start the animation. Thanks for the comment.

Cheers!

**Comment by yankeen** [comment]
Hi,

Thanks for the update!

It works fine, but now if I set nodeFancyEntrance as true there is no animation at all...

Thanks!

**Comment by martin-lundgren** [comment]
Hi,

Oops, thanks for the heads-up! It is fixed now.

You're most welcome!

**Comment by yankeen** [comment]
Thanks a lot!

All works well, but for some reason, there is a problem with IE. The first initial version works well in IE.

Thanks again :)

**Comment by martin-lundgren** [comment]
Hum, yes, you're right. The bug is resolved now, and everything should work.

Thanks for the testing, please let me know if you find something else! (:

**Comment by yankeen** [comment]
Hi,

There is one more change that appeared after the update. Black color appeared in the filled polygons. In the preview, this is not visible since the background is set as a shade of gray: #717171. If I change the background color to some bright color, the black color is clearly visible in the filled polygons, even if I set nodeFillColor as absolutely white #ffffff.

Thanks

**Comment by martin-lundgren** [comment]
Hi,

Thank you for the comment! (: 

Actually, that's not due to a bug, but a new feature. I added the option for gradient color, and default is #323232. You can turn it off by setting "nodeFillGradientColor" to null. But that's a good point, default should probably be null.

Cheers

**Comment by yankeen** [comment]
Great - an excellent new opportunity, by the way, expands the possibilities for creativity!!!

Thanks :)
