### ISSUE TITLE
Multiple Colors for fill

### ISSUE THREAD

**Issue by krebbi** [revoltera/polygonizr#4]
Great plugin! 

Is it possible to define more than one nodeFillColor? 

Cheers

**Comment by martin-lundgren** [comment]
Hi,

You mean have the different dots in various colors? No, it's not supported, but it is a good idea.

I'm currently working on a new version, hope to have it up soon. I'll add your comment to my list of things to look into till the next publish.

**Comment by krebbi** [comment]
Hi,

no, I mean the polygon filling. Would be nice to have an array of colors which will be picked randomly.

**Comment by martin-lundgren** [comment]
Hi again,

Updated the plugin and added your suggestion with color arrays, have a look at the sample file "spiral spin" for an example.

**Comment by krebbi** [comment]
Great work, thanks!

just two questions: 

nodeFillAlpha: 1 doesn't seem to have no alpha for the fill?

Is there a way to fill all spaces? 

![Bildschirmfoto 2021-07-13 um 16 33 22](https://user-images.githubusercontent.com/3884521/125471051-270d81ed-0c3d-421c-82c1-788f38487e83.png)

**Comment by martin-lundgren** [comment]
Hi,

Made some changes to how the relations between nodes are drawn. Now you should be able to fill all the spaces between connected nodes by setting "numberOfNodes" to whatever number of nodes you want and "numberOfUnconnectedNode" to 0 (and yes, keep nodeFillAlpha to > 0). Note that some spaces may occur as "coincidences" in the pattern, and not created by actual nodes being connected.

Give it a try and see if it solved your issue.

**Comment by krebbi** [comment]
Looks like I'm to stupid....

I'm trying to make something like this: https://www.freepik.com/free-vector/low-poly-style-camouflage-pattern-texture-background_8152345.htm#page=1&query=camouflage&position=9

Here's my Code:

`
    let $mycanvas = $('#mycanvas');
    let xdist = 120;
    let ydist = 120;
    let xnodes = $mycanvas.width() / xdist;
    let ynodes = $mycanvas.height() / ydist;
    let mynumberOfNodes = xnodes * ynodes;

    let xnodecount = 0;
    let ynodecount = 1;

    function randomNumber(min, max) {
      return Math.random() * (max - min) + min;
    }

    $mycanvas.polygonizr({
      canvasHeight: $(this).height(),
      canvasWidth: $(this).width(),
      nodeFancyEntrance: true,
      nodeRelations: 4,
      restNodeMovements: 0,
      node3dRotate: false,
      node3dRotateDepthAlpha: 1,
      node3dDepthDistance: 50,
      duration: 15,
      numberOfNodes: mynumberOfNodes,
      numberOfUnconnectedNode: 0,
      ConnectUnconnectedNodes: true,
      //ConnectUnconnectedNodesDistance: 400,
      nodeFillAlpha: 1,
      nodeLineAlpha: 0,
      nodeDotSize: 0,
      nodeFillColor: ["204, 202, 145", "175, 166, 116", "102, 83, 54", "80,98,61","115,135,87","55,58,40"],
      nodeFillColorColoringSchema: "random",
      nodeFillGradientColor: ["204, 202, 145", "175, 166, 116", "102, 83, 54", "80,98,61","115,135,87","55,58,40"],
      nodeFillGradientColoringSchema: "random",
      nodeMovementDistance: 100,
      randomizePolygonMeshNetworkFormation: false,
      specifyPolygonMeshNetworkFormation: function (i) {
        let adjust = randomNumber(-10,30);
        let xadjust = 0;
        if(ynodecount % 2 === 0) {
          xadjust = xdist / 2;
        }
        if(xnodecount < xnodes) {
          xnodecount++;
        } else {
          xnodecount = 0;
          if(ynodecount < ynodes) {
            ynodecount++;
          }
        }
        return forEachNode = {
          // Full circle in the center of the canvas.
          x: xnodecount * xdist + xadjust,
          y: ynodecount * ydist - adjust
        };
      }
    });

    // Update size.
    $(window).resize(function () {
      $mycanvas.polygonizr("stop");
      xnodes = $mycanvas.width() / xdist;
      ynodes = $mycanvas.height() / ydist;
      mynumberOfNodes = xnodes * ynodes;
      $mycanvas.polygonizr({
        nodeFancyEntrance: false,
        canvasHeight: $(this).height(),
        canvasWidth: $(this).width()
      });

      $mycanvas.polygonizr("refresh");
    });
`

Any ideas what I'm doing wrong?
